name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - style
      - build
    steps:
      - run: exit 0

  style:
    name: style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: temporary workaround - fmt all files under src
        run: cargo fmt -- --check $(find . -name '*.rs' -print)

  build:
    name: build
    strategy:
      matrix:
        config:
          - host: ubuntu-latest
          - host: windows-latest
          - host: macos-latest
    needs: [style]
    runs-on: ${{ matrix.config.host }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
